//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progect_Ezz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usere
    {
        public Nullable<int> User_Pass { get; set; }
        public int Use_id { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public string Email { get; set; }
        public string passworde { get; set; }
        public string Addresse { get; set; }
        public Nullable<int> Phone { get; set; }
    }
}
